
    var xingqing={};
    xingqing.jiuyeNews1={
        "success":"成功",
        "data":{
            "list":[
                {
                   "jieduan":"阶段一",
                   "img":"img/xq101.jpg",
                   "title":"前端零基础入门",
                   "center":"5步骤|33门课|52小时",
                   "bottomnum":"6777",
                   "bottomprice":"¥568.00"
                },
                {
                    "jieduan":"阶段二",
                    "img":"img/xq102.jpg",
                    "title":"响应式开发与常用框架",
                    "center":"5步骤|30门课|36小时",
                    "bottomnum":"2032",
                    "bottomprice":"¥658.00"
                 },
                 {
                    "jieduan":"阶段三",
                    "img":"img/xq103.jpg",
                    "title":"组件化思想开发电商网页",
                    "center":" 4步骤|31门课|62小时",
                    "bottomnum":"1357",
                    "bottomprice":"¥758.00"
                 },
                 {
                    "jieduan":"阶段四",
                    "img":"img/xq104.jpg",
                    "title":"热门框架Vue开发WebApp",
                    "center":" 4步骤|17门课|32小时",
                    "bottomnum":"793",
                    "bottomprice":"¥658.00"
                 }
            ]
        }
    }
    xingqing.jiuyeNews2={
        "success":"成功",
        "data":{
            "list":[
                {
                   "jieduan":"阶段一",
                   "img":"img/xq201.jpg",
                   "title":"Java零基础入门",
                   "center":"3步骤|27门课|40小时",
                   "bottomnum":"7098",
                   "bottomprice":"¥358.00"
                },
                {
                    "jieduan":"阶段二",
                    "img":"img/xq202.jpg",
                    "title":"从网页搭建入门Java Web",
                    "center":"5步骤|28门课|38小时",
                    "bottomnum":"1985",
                    "bottomprice":"¥568.00"
                 },
                 {
                    "jieduan":"阶段三",
                    "img":"img/xq203.jpg",
                    "title":"Java数据库开发与实战应用",
                    "center":"2步骤|12门课|25小时",
                    "bottomnum":"1833",
                    "bottomprice":"¥568.00"
                 },
                 {
                    "jieduan":"阶段四",
                    "img":"img/xq204.jpg",
                    "title":"SSM主流框架入门与综合项目实战",
                    "center":"4步骤|19门课|35小时",
                    "bottomnum":"1641",
                    "bottomprice":"¥628.00"
                 }
            ]
        }
    }

    xingqing.jiuyeNews3={
        "success":"成功",
        "data":{
            "list":[
                {
                   "jieduan":"阶段一",
                   "img":"img/xq301.jpg",
                   "title":"Android零基础入门",
                   "center":" 5步骤|43门课|57小时",
                   "bottomnum":"2047",
                   "bottomprice":"¥499.00"
                },
                {
                    "jieduan":"阶段二",
                    "img":"img/xq302.jpg",
                    "title":"Android网络操作与数据存储",
                    "center":"4步骤|22门课|30小时",
                    "bottomnum":"791",
                    "bottomprice":"¥488.00"
                 },
                 {
                    "jieduan":"阶段三",
                    "img":"img/xq303.jpg",
                    "title":"Android数据通信开发与应用",
                    "center":"4步骤|21门课|24小时",
                    "bottomnum":"813",
                    "bottomprice":"¥468.00"
                 },
                 {
                    "jieduan":"阶段四",
                    "img":"img/xq304.jpg",
                    "title":"Android多媒体开发与应用",
                    "center":"4步骤|19门课|28小时",
                    "bottomnum":"533",
                    "bottomprice":"¥499.00"
                 }
            ]
        }
    }

    xingqing.jiuyeNews4={
        "success":"成功",
        "data":{
            "list":[
                {
                   "jieduan":"阶段一",
                   "img":"img/xq401.jpg",
                   "title":"PHP小白零基础入门",
                   "center":"5步骤|26门课|48小时",
                   "bottomnum":"486",
                   "bottomprice":"¥628.00"
                },
                {
                    "jieduan":"阶段二",
                    "img":"img/xq402.jpg",
                    "title":"PHP常用技术与ThinkPHP5框架开发",
                    "center":"4步骤|19门课|45小时",
                    "bottomnum":"577",
                    "bottomprice":"¥668.00"
                 },
                 {
                    "jieduan":"阶段三",
                    "img":"img/xq403.jpg",
                    "title":"PHP典型功能与Laravel5框架开发",
                    "center":"4步骤|19门课|30小时",
                    "bottomnum":"244",
                    "bottomprice":"¥668.00"
                 },  
            ]
        }
    }